### ISSUE TITLE
Close button missing & Available/Missing indicator absent from requests

### ISSUE THREAD

**Issue by mcleodd10** [Archmonger/Blackberry-Themes#26]
The X Close button appears to be missing using either organizr or on top of burry css.
When unthemed there's usually a red or green triangle in the corner of posters on the homepage for requests/ombi; which seem to be missing entirely for bbf organizr. They're partially visible using the ontop of burry theme as only unavailable titles have a red indicator, which works fine for indicating which titles are available.
![bbf_example](https://user-images.githubusercontent.com/24360832/53616324-e97e1c00-3b96-11e9-9c7b-8cc475609ba2.PNG)

**Comment by Archmonger** [comment]
These were intentional modifications made to simplify the user experience. However, I agree I shouldn't have forced them upon people. They will be optional soon as we are restructuring our organizr themes into two new files. `bbf_organizr.css` which will now be a fork of Burry's plex theme (rather than our own custom theme), and `bbf_organizr_minimal_edition.css` which will contain the modifications I believe simplifies the user experience by reducing the amount of buttons and colors visible on the page.
